language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry install
script: poetry run pytest
after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && poetry run sphinx-build docs docs/_build
deploy:
  - provider: script
    script: poetry publish --build -u $PYPI_USER -p $PYPI_PASSWORD
    on:
      tags: true
  - provider: pages
    github-token: $GITHUB_TOKEN
    committer-from-gh: true
    skip-cleanup: true
    local-dir: docs/_build
    on:
      branch: master
